#!/usr/bin/env ruby
require 'rubygems'

gem "xcodeproj", "~> 1.5.4"

require 'xcodeproj'
require 'pathname'
require 'fileutils'

# Getting a reference to the Xcode project
unity_project_root_path = File.expand_path(File.dirname($0)) + "/../../iOS"
build_path = (ARGV[0]) ? ARGV[0] : unity_project_root_path # + "/build"
xcode_project_path = build_path + "/Unity-iPhone.xcodeproj"
xcode_project = Xcodeproj::Project.open(xcode_project_path)
xcode_project.initialize_from_file()

# System frameworks and libraries needed by mParticle
system_frameworks = ["Accounts", "AdSupport", "CoreTelephony", "Foundation", "Security", "Social", "SystemConfiguration", "UIKit", "iAd", "UserNotifications"]
system_libraries = ["sqlite3", "z"]

# Iterate through each project target and adds: system frameworks, libraries, and -ObjC
xcode_project.targets.each do |target|
    target.add_system_framework(system_frameworks)

    target.add_system_library(system_libraries)

    build_configurations = target.build_configurations
    build_configurations.each do |build_configuration|
        contains_objc = false
        other_linker_flags = target.build_settings(build_configuration.name)["OTHER_LDFLAGS"]
        if other_linker_flags
            other_linker_flags.each do |linker_flag|
                if linker_flag.eql? "-ObjC" then
                    contains_objc = true
                    break
                end
           end
        else
            other_linker_flags = []
        end
    
        if !contains_objc then
            other_linker_flags << "-ObjC"
        end
    end
end

# Saves Xcode project
xcode_project.save()
