name: Checks

on: [push, pull_request]

jobs:
  pr-branch-check-name:
    name: "Check PR for semantic branch name"
    if: ${{ github.event.pull_request }}
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-check-name.yml@stable
  pr-title-check:
    name: "Check PR for semantic title"
    if: ${{ github.event.pull_request }}
    uses: mParticle/mparticle-workflows/.github/workflows/pr-title-check.yml@stable
  pr-branch-target-gitflow:
    name: "Check PR for semantic target branch"
    if: ${{ github.event.pull_request }}
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-target-continuous.yml@stable
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    needs: [pr-branch-check-name, pr-title-check, pr-branch-target-gitflow]
    if: always() && !failure()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
  buildAndroidSampleApp:
    name: Build Android Sample app
    needs: [pr-branch-check-name, pr-title-check, pr-branch-target-gitflow]
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: 2020.3.32f1
          unity-modules: android
      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
      - name: "Build Android Sample app"
        run: ./buildscript.sh; ./testAndroidBuild.sh
  buildiOSSampleApp:
    name: Build Android Sample app
    needs: [pr-branch-check-name, pr-title-check, pr-branch-target-gitflow]
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: 2020.3.32f1
          unity-modules: android
      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
      - name: "Build iOS Sample app"
        run: ./buildscript.sh; ./testIOSBuild.sh


